package com.oropeza.urbanapp.core.events

object UrbanEventTypes {
    const val PLATFORM_BOOTSTRAP_STARTED = "PLATFORM_BOOTSTRAP_STARTED"
    const val PLATFORM_BOOTSTRAP_SUCCESS = "PLATFORM_BOOTSTRAP_SUCCESS"
    const val PLATFORM_BOOTSTRAP_WARNING = "PLATFORM_BOOTSTRAP_WARNING"
    const val PLATFORM_BOOTSTRAP_FAILED = "PLATFORM_BOOTSTRAP_FAILED"
    
    const val IDENTITY_READY = "IDENTITY_READY"
    const val WORKSPACE_READY = "WORKSPACE_READY"
    
    const val LICENSE_STATUS_CHANGED = "LICENSE_STATUS_CHANGED"
    const val PERMISSION_CHECKED = "PERMISSION_CHECKED"
    
    const val SYNC_REQUESTED = "SYNC_REQUESTED"
    const val SYNC_COMPLETED = "SYNC_COMPLETED"
    const val SYNC_FAILED = "SYNC_FAILED"
    
    const val HEARTBEAT_ENQUEUED = "HEARTBEAT_ENQUEUED"
    const val DIAGNOSTICS_REQUESTED = "DIAGNOSTICS_REQUESTED"
    
    const val ASD_TRIP_CREATED = "ASD_TRIP_CREATED"
    const val ASD_TRIP_CLOSED = "ASD_TRIP_CLOSED"
    const val ASD_EVENT_CREATED = "ASD_EVENT_CREATED"
}
