package com.oropeza.urbanapp.core.events

object UrbanEventTypes {
    const val PLATFORM_BOOTSTRAP_STARTED = "PLATFORM_BOOTSTRAP_STARTED"
    const val PLATFORM_BOOTSTRAP_SUCCESS = "PLATFORM_BOOTSTRAP_SUCCESS"
    const val PLATFORM_BOOTSTRAP_WARNING = "PLATFORM_BOOTSTRAP_WARNING"
    const val PLATFORM_BOOTSTRAP_FAILED = "PLATFORM_BOOTSTRAP_FAILED"
    
    const val IDENTITY_READY = "IDENTITY_READY"
    const val WORKSPACE_READY = "WORKSPACE_READY"
    
    const val LICENSE_STATUS_CHANGED = "LICENSE_STATUS_CHANGED"
    const val PERMISSION_CHECKED = "PERMISSION_CHECKED"
    
    const val SYNC_REQUESTED = "SYNC_REQUESTED"
    const val SYNC_COMPLETED = "SYNC_COMPLETED"
    const val SYNC_FAILED = "SYNC_FAILED"
    
    const val CONFIGURATION_FETCH_STARTED = "CONFIGURATION_FETCH_STARTED"
    const val CONFIGURATION_FETCH_SUCCESS = "CONFIGURATION_FETCH_SUCCESS"
    const val CONFIGURATION_FETCH_FAILED = "CONFIGURATION_FETCH_FAILED"
    const val CONFIGURATION_LOADED = "CONFIGURATION_LOADED"
    const val CONFIGURATION_WARNING = "CONFIGURATION_WARNING"
    
    const val HEARTBEAT_ENQUEUED = "HEARTBEAT_ENQUEUED"
    const val DIAGNOSTICS_REQUESTED = "DIAGNOSTICS_REQUESTED"
    
    const val ASD_TRIP_CREATED = "ASD_TRIP_CREATED"
    const val ASD_TRIP_CLOSED = "ASD_TRIP_CLOSED"
    const val ASD_EVENT_CREATED = "ASD_EVENT_CREATED"

    const val ASD_TRIP_ENQUEUED_FOR_SYNC = "ASD_TRIP_ENQUEUED_FOR_SYNC"
    const val ASD_EVENT_ENQUEUED_FOR_SYNC = "ASD_EVENT_ENQUEUED_FOR_SYNC"
    const val ASD_TRACK_CHUNK_ENQUEUED = "ASD_TRACK_CHUNK_ENQUEUED"
    const val ASD_TRIP_SYNC_READY = "ASD_TRIP_SYNC_READY"
    
    const val ASD_TRIP_SYNC_REQUESTED = "ASD_TRIP_SYNC_REQUESTED"
    const val ASD_TRIP_SYNC_STATUS_VIEWED = "ASD_TRIP_SYNC_STATUS_VIEWED"
}
