package com.oropeza.urbanapp.core.config

object UrbanFeatureFlags {
    const val ASD_ENABLED = "ASD_ENABLED"
    const val ASD_EXPORT_ENABLED = "ASD_EXPORT_ENABLED"
    const val CLOUD_SYNC_ENABLED = "CLOUD_SYNC_ENABLED"
    const val HEARTBEAT_ENABLED = "HEARTBEAT_ENABLED"
    const val DIAGNOSTICS_ENABLED = "DIAGNOSTICS_ENABLED"
    const val LICENSING_ENFORCEMENT_ENABLED = "LICENSING_ENFORCEMENT_ENABLED"
    const val REALTIME_ENABLED = "REALTIME_ENABLED"
    const val ANALYTICS_ENABLED = "ANALYTICS_ENABLED"
    const val REMOTE_CONFIG_ENABLED = "REMOTE_CONFIG_ENABLED"
}
